name: sj
ui: mocha-qunit
# html: templates.html
scripts:
  - "./test/precompiled/marker.js"
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
